name: LightEvents
main: LightEvents
version: 0.1
commands:
  event:
    description: Admin stuff regarding the event.
    usage: /event <action>
    aliases: [settings, setup, s, e]
    permission: lightevents.admin
  bingo:
    description: View all bingo items
    usage: /b & /bingo
    aliases: [b, bg, bi, bin, bgo]
  teams:
    description: View all teams and their progression
    usage: /teams
    aliases: [t, te]
  cancel:
    description: Cancel the server shutdown after the event ended.
    usage: /cancel
    permission: lightevents.admin
  bp:
    description: See the team inventory
    usage: /bp
  shutdown:
    description: When the server shutdown got cancelled, "uncancel" it to delete all remaining worlds and kick all players.
    usage: /shutdown